import AppKit
import IOKit.ps
import UniformTypeIdentifiers

/// Watches the system pasteboard and files every copy.
///
/// `NSPasteboard` has no change notification — no delegate, no KVO, nothing to
/// subscribe to. All it offers is `changeCount`, an integer that goes up every
/// time anything writes to it. So this polls that one integer; when it has not
/// moved, the tick returns without touching the pasteboard, the database or
/// the UI, which is why a sub-second timer costs effectively nothing.
@MainActor
final class ClipboardMonitor {
    private let store: ClipStore
    private let settings: AppSettings
    private let pasteboard = NSPasteboard.general

    private var timer: Timer?
    private var lastChangeCount: Int
    private var ticksSincePowerCheck = 0
    private var interval: TimeInterval = ClipboardMonitor.intervalOnAC

    private static let intervalOnAC: TimeInterval = 0.3
    private static let intervalOnBattery: TimeInterval = 0.5
    /// About once a minute — the IOKit call costs far more than a tick.
    private static let ticksBetweenPowerChecks = 200

    /// Markers from the nspasteboard.org convention. Password managers stamp
    /// `Concealed` on what they copy; without this guard the history would be
    /// a plaintext password log. `Transient` and `AutoGenerated` mark content
    /// the user never meant to keep.
    private static let skippedTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    init(store: ClipStore, settings: AppSettings) {
        self.store = store
        self.settings = settings
        // Start from the current count: whatever was on the pasteboard before
        // launch is not a new copy.
        self.lastChangeCount = NSPasteboard.general.changeCount
    }

    func start() {
        guard timer == nil else { return }
        interval = Self.preferredInterval()
        schedule()
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// Call right after Cache itself writes to the pasteboard. The write bumps
    /// `changeCount` exactly like a user copy would; banking it here stops the
    /// next tick from filing Cache's own write as a new clip.
    func acknowledgeSelfCopy() {
        lastChangeCount = pasteboard.changeCount
    }

    /// Added in `.common` mode by hand: `Timer.scheduledTimer` uses `.default`,
    /// which stops firing while a menu is open.
    private func schedule() {
        let timer = Timer(timeInterval: interval, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.tick() }
        }
        timer.tolerance = interval * 0.2
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    private func tick() {
        checkPowerSourceIfDue()

        let changeCount = pasteboard.changeCount
        guard changeCount != lastChangeCount else { return }
        lastChangeCount = changeCount
        capture()
    }

    private func capture() {
        let types = pasteboard.types ?? []

        // Before a single byte of content is read. The count is already banked,
        // so a skipped item stays skipped rather than being retried.
        guard !types.contains(where: Self.skippedTypes.contains) else { return }
        guard !settings.isPaused else { return }

        let source = Self.currentSource()
        if let bundleID = source?.bundleID, settings.ignoredBundleIDs.contains(bundleID) { return }

        let kind = ClipKind.detect(pasteboard: pasteboard, types: types)
        guard !settings.ignoredKinds.contains(kind.rawValue) else { return }

        switch kind {
        case .file:
            guard let urls = pasteboard.readObjects(forClasses: [NSURL.self]) as? [URL], !urls.isEmpty else { return }
            // Several files land as one clip, newline-separated, the way the
            // Finder hands them over.
            store.insertText(urls.map(\.path).joined(separator: "\n"), kind: .file, source: source)

        case .image:
            guard let (data, type) = Self.imageData(from: pasteboard, types: types) else { return }
            let store = self.store
            // Encoding and thumbnailing happen off the main thread; the clip
            // appears the moment its files are written.
            Task {
                guard let stored = await ImageIngest.storePasteboardData(data, type: type) else { return }
                store.insertImage(stored, source: source)
            }

        case .text, .link, .code, .color:
            guard let text = pasteboard.string(forType: .string),
                  !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
            else { return }
            store.insertText(text, kind: kind, source: source)
        }
    }

    /// The most useful image flavour on offer: something already compressed
    /// beats TIFF, which is huge and gets re-encoded.
    private static func imageData(
        from pasteboard: NSPasteboard,
        types: [NSPasteboard.PasteboardType]
    ) -> (Data, UTType)? {
        let preference = ClipKind.imagePasteboardTypes.filter { $0 != .tiff } + [.tiff]
        for type in preference where types.contains(type) {
            if let data = pasteboard.data(forType: type), !data.isEmpty,
               let uti = UTType(type.rawValue) {
                return (data, uti)
            }
        }
        return nil
    }

    /// Whoever the user is working in. Cache's panels never activate the app,
    /// so the frontmost application is still the one that copied — unless one
    /// of Cache's own windows has the keyboard, in which case the copy came
    /// from Cache (selecting text in the preview, say).
    private static func currentSource() -> SourceApp? {
        if NSApp.keyWindow != nil {
            return SourceApp(name: "Cache", bundleID: Bundle.main.bundleIdentifier)
        }
        guard let app = NSWorkspace.shared.frontmostApplication else { return nil }
        return SourceApp(name: app.localizedName, bundleID: app.bundleIdentifier)
    }

    // MARK: - Power

    private func checkPowerSourceIfDue() {
        ticksSincePowerCheck += 1
        guard ticksSincePowerCheck >= Self.ticksBetweenPowerChecks else { return }
        ticksSincePowerCheck = 0

        let wanted = Self.preferredInterval()
        guard wanted != interval else { return }
        interval = wanted
        stop()
        schedule()
    }

    private static func preferredInterval() -> TimeInterval {
        ProcessInfo.processInfo.isLowPowerModeEnabled || isOnBattery() ? intervalOnBattery : intervalOnAC
    }

    private static func isOnBattery() -> Bool {
        guard let snapshot = IOPSCopyPowerSourcesInfo()?.takeRetainedValue(),
              let sources = IOPSCopyPowerSourcesList(snapshot)?.takeRetainedValue() as? [CFTypeRef]
        else { return false }

        return sources.contains { source in
            guard let description = IOPSGetPowerSourceDescription(snapshot, source)?
                .takeUnretainedValue() as? [String: Any]
            else { return false }
            return description[kIOPSPowerSourceStateKey] as? String == kIOPSBatteryPowerValue
        }
    }
}
